services:
  - type: web
    name: bolado-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: BOLADO_API_KEY
        generateValue: true
